services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: techno_sql

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong@123"

    volumes:
      - sql_data:/var/opt/mssql

    restart: always

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'YourStrong@123' -C -Q 'SELECT 1' || exit 1"
        ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s


  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: techno_api

    ports:
      - "5000:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Development

      SiteSettings__SqlConfigurations__ConnectionString: "Server=sqlserver,1433;Database=Techno_King;User Id=sa;Password=YourStrong@123;TrustServerCertificate=True"

      AllowedOrigins__0: "http://128.140.105.187:5173"

    depends_on:
      sqlserver:
        condition: service_healthy

    restart: always


  frontend:
    build:
      context: ./Front
      dockerfile: Dockerfile

    container_name: techno_front

    ports:
      - "5173:5173"

    depends_on:
      - api

    restart: always


volumes:
  sql_data:
